@echo off
REM ****************************************************************************
REM Vivado (TM) v2025.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Fri Oct 09 00:19:42 -0600 2026
REM SW Build 6140274 on Thu May 22 00:12:29 MDT 2025
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim lab_3_top_level_tb_behav -key {Behavioral:sim_1:Functional:lab_3_top_level_tb} -tclbatch lab_3_top_level_tb.tcl -view C:/Users/alexs/Desktop/2026-2027/453/ENEL453/lab3/lab_3_top_level_tb_behav.wcfg -log simulate.log"
call xsim  lab_3_top_level_tb_behav -key {Behavioral:sim_1:Functional:lab_3_top_level_tb} -tclbatch lab_3_top_level_tb.tcl -view C:/Users/alexs/Desktop/2026-2027/453/ENEL453/lab3/lab_3_top_level_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
